### PR TITLE
Feature recipe inventory List

### PR DESCRIPTION
**Pull request by AbuTalha3**
**In this PR I have**
- Implemented functionality to display a list of` inventories` `created` by the `logged-in user`.

### CODE REVIEW

**Comment by AbuTalha3** [comment]
**Linters show error on GitHub page only whereas corrected in Editor**
image

**Comment by AbuTalha3** [comment]
@sabry Can you please review the changes?

**Comment by AbuTalha3** [comment]
@sabry can you please review the changes?

**Review by sagieramos — APPROVED** [review]
Hi @AbuTalha3,
 
## Your task is approved.

Your task is complete!  You did a great job working on it :clap:. You can go ahead and merge it :shipit: 
Congratulations! 🎉 Keep up your great work :100: 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Pull request merged**
